version: "3"

services:
  webapp:
    build: ./list-app
    image: prison-wods-webapp
    container_name: webapp
    ports:
      - 8080:5000
    depends_on:
      - api

  api:
    build: ./api
    image: prison-wods-api
    container_name: api
    depends_on:
      - db

  db:
    image: mongo
    container_name: db
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
